Fix README
auth0-developer-hub/auth0-b2b-saas-starter pull request #17
Opened 2024-06-12 09:32 UTC by madebyankur

2024-06-12 19:36 UTC, matthewpereira requested changes

2024-06-12 19:36 UTC, matthewpereira commented on README.md
> +**Important: this will create and update entities in your Auth0 tenant – it is best to use a fresh/new tenant when bootstrapping. You can sign up for a free tenant at [https://auth0.com/signup?utm_so
This is backward - it'll display the full URL but clicked will direct users to the one without a query string. Could you reverse the [] content and the () content?

2024-06-12 19:36 UTC, matthewpereira commented on README.md
> +Once the script has successfully completed, a `.env.local` file containing the environment variables will be written to the root of your project directory.
What's the motivation for un-indenting this material? I think it previously 'nested' under `1. Run the following command:` as a result of the indentation.

2024-06-13 08:24 UTC, madebyankur commented on README.md
> +**Important: this will create and update entities in your Auth0 tenant – it is best to use a fresh/new tenant when bootstrapping. You can sign up for a free tenant at [https://auth0.com/signup?utm_so
Nice catch 🙇‍♂️

2024-06-13 08:42 UTC, madebyankur commented on README.md
> +Once the script has successfully completed, a `.env.local` file containing the environment variables will be written to the root of your project directory.
This wasn't formatted correctly as you can see on the `main` branch but I pushed some more updates - we don't need the single step here IMO.

2024-06-14 12:51 UTC, matthewpereira commented on README.md
> +   > Note: If you're running the application on a different port, adjust the provided localhost URL accordingly.
```suggestion

```

2024-06-14 12:51 UTC, matthewpereira commented on README.md
> +   > Note: If you're running the application on a different port, adjust the provided localhost URL accordingly.
This line is duplicated from 115 above.

2024-06-14 12:52 UTC, matthewpereira approved these changes

2024-06-14 12:52 UTC, merged